# Generated by Django 3.0 on 2020-08-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20200807_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
