# Generated by Django 3.0 on 2020-08-07 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20200807_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='captions',
            new_name='caption',
        ),
    ]
