# Generated by Django 3.1.6 on 2021-02-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='photos_pics', width_field='image_width'),
        ),
    ]
