# Generated by Django 3.1.6 on 2021-02-06 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20210206_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='published_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
