# Generated by Django 3.1.6 on 2021-02-06 21:21

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20210206_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='published_date',
            field=models.DateField(auto_now_add=True,default=django.utils.timezone.now()),
        ),
    ]
