# Generated by Django 3.1.6 on 2021-02-07 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20210206_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='published_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='photos.photos')),
            ],
        ),
    ]
