# Generated by Django 3.1.6 on 2021-02-07 11:54

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('photos', '0005_auto_20210207_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
